blank_issues_enabled: false
contact_links:
  - name: 📚 SDK Documentation
    url: https://github.com/permaweb/permaweb-libs?tab=readme-ov-file#permaweblibs
    about: Check the docs before opening a new issue.
