name: Auto Tag and Publish to NPM

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: permaweb/permaweb-libs/.github/workflows/build.yaml@main
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      id-token: write # to enable use of OIDC for npm provenance
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./sdk

      - name: Build
        run: npm run build
        working-directory: ./sdk

      - name: Publish to NPM with Semantic Release
        working-directory: ./sdk
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}